version: '3'

services:
  psql:
    container_name: todo_db_psql
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: 'todo_db'
      POSTGRES_USER: 'admin_db'
      POSTGRES_PASSWORD: 'YourNewStrong@Passw0rd'
    volumes:
      - ./.psql:/var/lib/psql
    ports:
      - '5433:5432'
